name: Testing on Windows OS

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  deno:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run tests
        run: deno test --allow-read
